test/system/system_test.go

each resource request takes 40 ~ 90s on ci. we can speed things up
considerably by creating a single resource covering all test cases.

unify system test

---

config/samples/redis/redis-crd.yaml
controllers/dynamic_resource_request_controller.go
controllers/promise_and_dynamic_resource_request_controller_test.go
controllers/util.go
lib/hash/hash_suite_test.go
lib/hash/hash_test.go
lib/hash/hasher.go
lib/pipeline/args.go
lib/pipeline/configure.go
lib/pipeline/configure_test.go
lib/pipeline/delete.go
lib/pipeline/labels.go
lib/pipeline/pipeline_suite_test.go
lib/pipeline/shared.go
lib/resourceutil/conditions.go
lib/resourceutil/resourceutil_suite_test.go
lib/resourceutil/util.go
lib/resourceutil/util_test.go
test/system/system_test.go

the workplacement controller is not yet responding to the updated work, so the pipeline outcome won't actually make to the destination just yet

feat: run a new pipeline job on updates

---

api/v1alpha1/promise_types.go
controllers/promise_and_dynamic_resource_request_controller_test.go
controllers/promise_controller.go
controllers/util.go

I recommend reviewing commit by commit. The last commit results in slightly uglier code, but I think its worth the tradeoff of not creating Works until we have everything else (apart from dynamic controller) created.

Fix finalizer race

---

controllers/destination_controller.go
lib/writers/s3.go

Reverts syntasso/kratix#30
Should have gone to dev 🤦

Revert "fix: remove log noise from kratix start up reconciliation"

---

controllers/destination_controller.go
lib/writers/s3.go

Reduce error logs

---

controllers/promise_controller.go
controllers/suite_test.go
main.go

Fixes 
https://github.com/syntasso/kratix/issues/27
https://github.com/syntasso/kratix/issues/34

fix: stop dynamic controller on promise deletion by restarting manager

---

controllers/promise_controller.go

Previously if Kratix crashed or restarted while a Promise was in deletion mode the dynamic controller wouldn't be running, which means the resource requests under the promise would all be stuck in a deletion state and never proceed.

fix: Ensure dynamic controller is started when deleting resource

---

controllers/dynamic_resource_request_controller_test.go
controllers/promise_controller.go
controllers/promise_controller_test.go
controllers/scheduler.go
hack/kratix-promise-release-test-hoster-image/main.go
lib/pipeline/configure.go
lib/workflow/reconciler.go
lib/writers/git.go
lib/writers/s3.go

Replaces #107 to base and merge into `dev` branch
Commit messages should be self explanatory. Most of them are picked up by my IDE.
Have run unit and system tests locally.

Tiny things

---

hack/platform/gitea-install.yaml
scripts/install-gitops
scripts/quick-start.sh
scripts/utils.sh

also: simplify the gitea deployment; no need for a database, sqlite3 does the job
solves https://github.com/syntasso/kratix/issues/112

fix: running kratix with git + podman

---

work-creator/scripts/update-status

fix(#118): don't overwrite whole status in last pipeline

---

api/v1alpha1/workplacement_types.go
config/crd/bases/platform.kratix.io_workplacements.yaml
controllers/destination_controller.go
controllers/scheduler.go
controllers/suite_test.go
controllers/workplacement_controller.go
controllers/workplacement_controller_test.go
lib/writers/git.go
lib/writers/s3.go
lib/writers/statestore_writer.go
lib/writers/writersfakes/fake_state_store_writer.go
main.go

- **refactor: merge writer funcs into a single one**
- **feat: surface version to the workplacement status**
- **feat: attempt to preserve version id on failures**

feat: surface writer metadata as status in workplacement

---

api/v1alpha1/promise_types.go
controllers/dynamic_resource_request_controller_test.go
controllers/promise_controller_test.go
controllers/scheduler.go
controllers/work_controller.go
lib/pipeline/delete_test.go
lib/pipeline/labels.go
scripts/install-jenkins.sh
work-creator/pipeline/work_creator_test.go

fix: remove deprecrated 'kratix-promise-id' label

fix: remove deprecrated 'kratix-promise-id' label

---

controllers/destination_controller.go
controllers/promise_controller.go
controllers/work_controller.go
controllers/work_controller_test.go
controllers/workplacement_controller.go

closes #166 
Set finalizer in works to clean up its workplacements before deleting work

fix: set finalizer in Works

---

main.go

fix: dont keep prepending to logger

---

api/v1alpha1/promise_webhook.go
config/default/webhookcainjection_patch.yaml
config/webhook/manifests.yaml

This reverts commit c4412357f1e0da0c19127d16f7802db62e9ae9c9.

Revert "fix: remove unused defaulting webhook from promise"

---

Dockerfile
Dockerfile.pipeline-adapter
work-creator/scripts/update-status

This required both introducing a multi-stage build and making sure to
enable ownership of a workspace for the nonroot user
resolves #215

chore: Remove root requirement for pipeline-adaptor image

---

api/v1alpha1/bucketstatestore_types.go
api/v1alpha1/gitstatestore_types.go
config/crd/bases/platform.kratix.io_bucketstatestores.yaml
config/crd/bases/platform.kratix.io_gitstatestores.yaml

adding some description for statestore fields

chore: add crd description for statestore

---

api/v1alpha1/pipeline_types.go
api/v1alpha1/pipeline_types_test.go
main.go

1. set allowPrivilegeEscalation: false by default for kratix containers
2. also add some additional logging

feat: set allowPrivilegeEscalation: false by default for kratix containers

---

main.go

Number of jobs to keep used to be configured via env var. This PR moves it to kratix configmap. It can be configured like so:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: kratix
namespace: kratix-platform-system
data:
config: |
numberOfJobsToKeep: 3
```

refactor: move jobs cleanup limit to kratix config

---

api/v1alpha1/pipeline_types.go
api/v1alpha1/pipeline_types_test.go
api/v1alpha1/promise_webhook.go
api/v1alpha1/promise_webhook_test.go

- **feat: propagate pipeline labels/annot to pod**
- **feat: add webhook for workflow labels validation**

feat: propagate workflow labels to pod

---

Dockerfile
Dockerfile.pipeline-adapter

* some security scanners will complain when this is not set

fix: set user on kratix and adapter dockerfiles

---

hack/destination/gitops-argo-resources-git.yaml

Example on argo applications that reconciles on `resources/` and `dependencies/`.

chore: argo applications setup

---

api/v1alpha1/pipeline_factory.go
lib/workflow/reconciler.go
lib/workflow/reconciler_test.go

fix: Don't delete destination selector configmaps when in use

---

controllers/destination_controller.go

This closes #230
When filepath.mode is set to none, canary namespace and configmaps should be written to the root of the destination.
Given two destinations, worker-1 with the default nested filepath mode, and worker-2 with filepath.mode set to `none`. Statestore looks like:
```
[2024-11-25 17:38:57 GMT]   116B STANDARD kratix/worker-1/dependencies/kratix-canary-namespace.yaml
[2024-11-25 17:43:03 GMT] 2.5KiB STANDARD kratix/worker-1/dependencies/redis/promise-configure/5058f/all-redis-operator-resources.yaml
[2024-11-25 17:43:03 GMT] 790KiB STANDARD kratix/worker-1/dependencies/redis/promise-configure/5058f/databases.spotahome.com_redisfailovers.yaml
[2024-11-25 17:38:57 GMT]   206B STANDARD kratix/worker-1/resources/kratix-canary-configmap.yaml
[2024-11-25 17:43:16 GMT]    29B STANDARD …
```

fix: canary documents respect destination file path mode

---

api/v1alpha1/healthrecord_types.go
config/crd/bases/platform.kratix.io_healthrecords.yaml
controllers/healthrecord_controller_test.go
test/system/healthchecks_test.go

chore: update healthRecord lastRun type to int64

---

hack/destination/gitops-tk-resources.yaml
scripts/quick-start.sh

this is a cross repo change and changes in the docs, marketplace, and enterprise repos depend on this.

chore: rename all references to kratix-bucket to kratix

---

lib/writers/s3.go

Context: https://github.com/minio/mc/issues/2398#issuecomment-367958032
Using the multi delete API call in GCS gets an error:
```
A header or query you provided requested a function that is not implemented.
```
Using a singular delete per object removes this.

fix: Don't use multi-delete s3 api call, not compatible with gcs

---

controllers/promise_controller.go

Use DeepEqual instead of comparing field by field. 
checking `len(oldReqs)+len(newReqs) == 0` because a non-nil empty slice and a nil slice (for example, []byte{} and []byte(nil)) are not deeply equal, https://pkg.go.dev/reflect#DeepEqual. In this specific case `promise.Status.RequiredPromises` when not set is `nil`, but the computed new required promises is initialized to `[]v1alpha1.RequiredPromiseStatus{}` and therefore won't be equal.

chore: simply comparison logic

---

.gitignore
Makefile
config/crd/kustomization.yaml
config/default/kustomization.yaml
config/default/webhookcainjection_patch.yaml
config/manager/kustomization.yaml
config/manager/pipeline-adapter-config.properties
config/rbac/kustomization.yaml

What it says on the tin!
NB: Once this is merged you'll need to delete your local `kustomize` binary in Kratix (at `./bin/kustomize`) so the Make targets can reinstall it and bump the version!

Upgrade Kustomize to v5

---

Makefile
controllers/dynamic_resource_request_controller.go
controllers/healthrecord_controller.go
controllers/healthrecord_controller_test.go
controllers/promise_controller.go
controllers/promise_controller_test.go
lib/resourceutil/util.go
lib/workflow/reconciler.go
lib/workflow/reconciler_test.go
main.go

This PR adds events for:
- resource health - _from the Health Record Controller_
- reconciling all resources - _from the PromiseController_
- Promise availability [under certain conditions; see #368] - _from the Promise Controller_
```
Events:
Type    Reason           Age                From               Message
----    ------           ----               ----               -------
Normal  PipelineStarted  95s                PromiseController  Configure Pipeline started: promise-pipeline0
Normal  PipelineStarted  89s                PromiseController  Configure Pipeline started: promise-pipeline1
Normal  Available        84s (x2 over 84s)  PromiseController  Promise is available
```
```
Events:
Type    Reason           Age   From                       Message
----    ------           ---- …
```

feat: introduce more events

---

test/kubeutils/cluster.go
test/system/rbac_test.go

In our RBAC system test suite, we use a test promise with a workflow permission set to a specific resource:
```
...
resource:
configure:
- apiVersion: platform.kratix.io/v1alpha1
kind: Pipeline
metadata:
name: rbac-res
spec:
rbac:
permissions:
- apiGroups: [""]
verbs: ["get", "list", "create", "update", "patch"]
resources: ["secrets"]
resourceNames: ["rbac-resource-secret"]
```
Workflows running successfully means it can get the resource. We don't have test coverage verifying that the workflow cannot get secrets other than "rbac-resource-secret". This PR adds this together with a new `KubectlAllowFail()` helper that will not assert on command exit code.

chore: add test coverage on generated rbac roles

---

config/rbac/role.yaml
internal/controller/destination_controller.go

relates to issue: https://github.com/syntasso/helm-charts/issues/32
add permission to create, delete, watch. These are permission we will need for this issue as well: https://github.com/syntasso/kratix/issues/247

chore: give operator statestore permission

---

.github/workflows/pr.yaml

Already running this checks in kratix test and publish workflow in the CI repo. Adding them to PR workflow for faster feedback since they are cheap to run.
Part of issue: https://github.com/syntasso/kratix/issues/355

ci: run govulncheck and snyk code scan in PR workflow

---

internal/controller/promise_controller.go
internal/controller/promise_controller_test.go

fix: promise stays available with scheduled reconcile

---

.github/workflows/pr.yaml
Makefile

Run core, system tests, integration tests all in parallel to speed up the workflow.

ci: run system tests and integration tests in parallel

---

internal/controller/promise_controller.go
internal/controller/promise_controller_test.go
internal/controller/shared.go

fixes https://github.com/syntasso/kratix/issues/415
The next reconciliation is now only scheduled after the configure pipeline is completed.

fix: check promise reconciliation

---

Makefile
scripts/quick-start.sh

- plus remove the gitea-cli and minio-cli install from make target

chore: add minio-cli installation to quick start script

---

api/v1alpha1/destination_types.go
config/crd/bases/platform.kratix.io_destinations.yaml

fix: set object default to ensure destination.spec.initWorkload

---

cmd/main.go

This PR makes the timeout for kratix leader election configurable. For some people, they might want this feature but do not want to renew the lease every 20 seconds.
To test, create a kratix-config configmap like so:
```
apiVersion: v1
kind: ConfigMap
metadata:
name: kratix
namespace: kratix-platform-system
data:
config: |
controllerLeaderElection:
leaseDuration: 100s
renewDeadline: 100s
retryPeriod: 100s
```

feat: controller leader election timeouts configurable

---

test/core/core_test.go

LRE has different destination names.

chore: parameterise destinationName in core tests

---

Makefile
test/core/assets/promise-v2.yaml
test/core/assets/promise.yaml

Necessary changes for running core test against LRE.

chore: can run core test against non-kind env

---

cmd/main.go

GitStateStore and BucketStateStore controller watches Secrets. Controller runtime creates secret cache for the watch and by default, it creates caches for all secrets in the k8s cluster.
This means that in a busy cluster with lots of secrets, the default cache uses a lots of memory.
This PR adds the functionality for users to choose to turn on label selector cache for Secrets to limit memory usage. Default behavior does not change, to use this feature, they can configure the kratix config:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: kratix
namespace: kratix-platform-system
data:
config: |
selectiveCache: true
```
Users must label secrets that's used for kratix objects with the label selector when we create the cache `app.kubernetes.io/part-of=kratix`. Or else kratix controller …

feat: secret cache by label selector to limit memory usage of kratix controller

---

internal/controller/promise_controller.go
lib/resourceutil/work.go
lib/workflow/reconciler.go
lib/workflow/reconciler_test.go
work-creator/pipeline/cmd/work-creator/main.go
work-creator/pipeline/work_creator.go
work-creator/pipeline/work_creator_test.go

also:
+ update work-creator "work-type" selector to be set to the provided
label

chore: use more labels when filtering works

---

api/v1alpha1/pipeline_factory.go
api/v1alpha1/pipeline_types_test.go

chore: allow separate scheduling configmap

---

lib/writers/git.go
lib/writers/git_test.go

closes #463 
This PR dynamically gets the ssh user when connecting to git state store by parsing the given URL. The ssh user were hard coded to `git` which limits how people can configure kratix to connect to their git state store via ssh.

feat: support GitStateStore ssh with users other than 'git'

---

lib/workflow/reconciler.go
work-creator/pipeline/work_creator.go

Co-authored-by: Derik Evangelista <derik@syntasso.io>

feat: add more generic filtering for workflow types

---

api/v1alpha1/pipeline_factory.go
api/v1alpha1/pipeline_types_test.go

fix: add documented but missing env vars

---

internal/controller/destination_controller.go
internal/controller/workplacement_controller.go

- with helpers the flow of the reconcile() is clearer

chore: refactor workplacement reconcile()

---

.golangci-required.yml
api/v1alpha1/promise_types.go
config/crd/bases/platform.kratix.io_destinations.yaml
internal/controller/assets/promise-with-requirements.yaml
internal/controller/dynamic_resource_request_controller.go
internal/controller/promise_controller.go
internal/controller/promise_controller_test.go
lib/resourceutil/util.go
lib/workflow/reconciler.go
lib/workflow/reconciler_test.go
test/core/core_test.go

closes #477 
When requirements are fulfilled, works ready and pipelines run successfully
```
Status:
API Version:  marketplace.kratix.io/v1alpha1
Conditions:
Last Transition Time:  2025-06-17T14:24:06Z
Message:               Ready to fulfil resource requests
Reason:                PromiseAvailable
Status:                True
Type:                  Available
Last Transition Time:  2025-06-17T14:24:03Z
Message:               Pipelines completed
Reason:                PipelinesExecutedSuccessfully
Status:                True
Type:                  ConfigureWorkflowCompleted
Last Transition Time:  2025-06-17T14:24:06Z
Message:               Reconciled
Reason:                Reconciled
Status:                True
Type:                  Reconciled
Last Transition Time:  2025-06-17T14:23:52Z …
```

feat: Promise status and events improvement

---

scripts/helm-e2e-test.sh

Related: https://github.com/syntasso/helm-charts/commit/b544aa3b5e7bf8d0fd0cec9f8c36d0504a56d732

chore: remove deprecated destination chart from e2e test script
