syntasso/kratix

Makefile, docs/detailed-start.md, docs/quick-start.md, scripts/quick-start.sh
Our current workshop falls over on kubernetes `1.25` as the postgres operator isn't supported for `1.25` 
https://github.com/zalando/postgres-operator/issues/1999
```
Looks like PodDisruptionBudget policy/v1beta1 got removed (policy/v1 is the new apiVersion), which is causing the Postgres Operator to fail to creat the instances
$ k logs postgres-operator-6649b754cd-5w42h msg="could not create cluster: could not create pod disruption budget: the server could not find the requested resource" cluster-name=default/acid-minimal-cluster pkg=controller worker=0
```
this PR pins all of our `kind create cluster` to `1.24`
```
rg "kind create"
scripts/quick-start.sh
176:    if ! run kind create cluster --name platform --image kindest/node:v1.24.0 \
196:    if ! run kind create cluster --name worker …
```
=> Pin k8s version to 1.24

api/v1alpha1/promise_types.go, api/v1alpha1/work_types.go, config/crd/bases/platform.kratix.io_promises.yaml, config/crd/bases/platform.kratix.io_works.yaml, samples/jenkins/request-pipeline-image/jenkins_instance.yaml
for backstage, we want to include non-k8s resources to the WCR; the kubebuilder annotation includes validations on the presence of `metadata` and `spec`, and only accepts certain keys under those objects.
[#184161539]
=> feat: allow for non-k8s resources on WCR

lib/resourceutil/util.go, lib/resourceutil/util_test.go
when the pipeline gets retriggered for a particular resource, the
controller will add a 'message: Pending' status to the resource.
however, the old code was accidentaly wiping out any other status from
the object; as a side effect, pipelines that relied on information
persisted in the `status` field wouldn't have that information
available.
this commit changes the `SetStatus` utils to utilise the existing
resource `status` as a base (if that exists).
=> fix: overwriting status on pipeline re-run

.circleci/config.yml, Makefile, scripts/build-images, scripts/quick-start.sh, scripts/teardown
oftentimes we don't need to fully recreate the kubernetes environment to run the system tests. this commit adds a few extra targets to make it possible to reuse an existing kind cluster
[#186442211]
This commit updates the Makefile as follows
```diff
Usage:
make <target>
General
help             Display this help.
Kubebuilder
manifests        Generate WebhookConfiguration, ClusterRole and CustomResourceDefinition objects.
generate         Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
Environment
+ teardown         Delete all Kratix resources from the Platform cluster
+ fast-quick-start  Install Kratix without recreating the local clusters
quick-start      Recreates the clusters and install Kratix
prepare-platform-as-destination  Installs flux …
```
=> feat: add targets to cleanup a kratix installation

controllers/assets/redis-simple-promise-updated.yaml, controllers/assets/redis-simple-promise.yaml, controllers/promise_controller.go, controllers/promise_controller_test.go, controllers/promiserelease_controller.go, controllers/promiserelease_controller_test.go, controllers/util.go, test/system/assets/bash-promise/promise-release.yaml, test/system/assets/bash-promise/promise-with-destination-selectors-updated.yaml, test/system/assets/bash-promise/promise-with-destination-selectors.yaml, test/system/assets/bash-promise/promise.yaml, test/system/system_suite_test.go, test/system/system_test.go
the promise version should be defined in the promise yaml itself.
the promise can define its version by setting the following label:
kratix.io/promise-version: <version>
* if a promise release sets a version, and the version matches the version in the promise release, all is good
* if a promise release doesn't set a version, its version will be set to the version of the promise found on the url
* if the promise release version doesn't match the promise version found on the url, the promise won't be installed.
[#186673378](https://www.pivotaltracker.com/story/show/186673378)
=> feat: release to respect promise-defined version

controllers/destination_controller.go, controllers/scheduler.go, controllers/scheduler_test.go, scripts/quick-start.sh
finishes: #186442323
https://www.pivotaltracker.com/story/show/186442323
Scheduler tests are now fast, and have some additional coverage.
Best reviewed commit-by-commit (see commit messages for more context on each one!).
-----
End result: 27 Scheduler tests take 0.032s to run, and including setup/teardown they take 2.7s ⏱️
```
[Syntassos-MBP] [scheduler-envtest-removal] [kratix] 
> ginkgo run -r controllers
Running Suite: Controller Suite - /Users/richbartoncooper/Projects/kratix/controllers
=====================================================================================
Random Seed: 1703155204
Will run 27 of 74 specs
SSSSSS•••••••••••••••••••••••••••SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 27 of 74 Specs in 0.032 seconds
SUCCESS! -- 27 Passed | 0 Failed | 0 Pending | 47 …
```
=> chore: migrate Scheduler tests from envtest to fake client

api/v1alpha1/promise_types.go, controllers/dynamic_resource_request_controller.go, controllers/util.go, lib/pipeline/assets/promise.yaml, lib/pipeline/assets/resource-request.yaml, lib/pipeline/delete.go, lib/pipeline/delete_test.go, lib/pipeline/shared.go, test/system/assets/bash-promise/promise-v1alpha2.yaml, test/system/assets/bash-promise/promise-with-destination-selectors-updated.yaml, test/system/assets/bash-promise/promise-with-destination-selectors.yaml, test/system/assets/bash-promise/promise.yaml, test/system/system_test.go
#67 introduced a bug which meant that the ServiceAccount used in delete pipelines wasn't configured correctly, which meant deletes failed.
tl;dr - we started to use the `Kind` and not the plural for the Role resource, and didn't catch it in tests because `bash` and `redis` both have identical singular and plural versions 😢
This PR fixes the bug by passing in the plural when creating the delete pipeline, and also makes `bashes` the plural of `bash` so we have some coverage of this case in the system tests.
(There's also a `redis` promise used in the system tests, so we still have some coverage of the identical-singular-plural case.)
See [here](https://syntasso.slack.com/archives/C044T9ZFUMN/p1704970369264829?thread_ts=1704900358.243089&cid=C044T9ZFUMN) in Slack for more detail 🧵
=> Fix delete pipelines

Makefile, hack/kratix-promise-release-test-hoster-image/Dockerfile, hack/kratix-promise-release-test-hoster-image/build_and_push.sh, hack/kratix-promise-release-test-hoster-image/deployment.yaml, hack/kratix-promise-release-test-hoster-image/go.mod, hack/kratix-promise-release-test-hoster-image/go.sum, hack/kratix-promise-release-test-hoster-image/main.go, lib/writers/git.go, test/system/assets/bash-promise/deployment.yaml, test/system/assets/bash-promise/promise-release.yaml, test/system/system_suite_test.go, test/system/system_test.go
Changes
- Expose environment variables for cluster kubeconfigs
- Pushed the bash images to dockerhub
- Use an in-cluster pod to handle the promiserelease curls
- Skip checking the minio bucket. I almost wanted to delete this test and didn't, I don't think its worth making it work on any s3 provider
=> make system tests runnable on non kind clusters

controllers/dynamic_resource_request_controller_test.go, controllers/promise_controller_test.go, controllers/shared.go, controllers/shared_test.go, lib/resourceutil/util.go
[Story](https://www.pivotaltracker.com/story/show/186934123)
Currently we never delete old jobs/pods. If a resource is updated 100 times, we will have a 100 pods. This PR changes it so we only ever keep the last five jobs/pods for a promise/resource. In the future it will be configurable.
Below is the output from having a promise and resource request updated 5 times:
```
k get pods
default                  configure-pipeline-redis-3ee9c-dxwjn                 0/1     Completed   0          2m6s
default                  configure-pipeline-redis-7b634-ds2hs                 0/1     Completed   0          6s
default                  configure-pipeline-redis-831ed-kd2tb                 0/1     Completed   0          52s
default                  configure-pipeline-redis-bbd43-ftskx …
```
=> feat: Delete old jobs, only keep the last five

lib/pipeline/configure.go, lib/pipeline/delete.go, lib/pipeline/delete_test.go, lib/pipeline/shared.go
This commit ensures that we pass through all the fields from the Kratix Pipeline object to the Pods that are created for a delete Job.
=> feat: ensure all delete pipeline params are passed to pods

hack/platform/gitea-install.yaml, scripts/install-gitops, scripts/quick-start.sh, scripts/utils.sh
There are a few commits here, but the fix is that the secrets were not properly created for git. That is fixed in the `install-gitops` script.
Note that this work uncovered that the quick-start must be run with --git-and-minio to work with backstage config. That is out of scope for this work, but is something we may want to untangle in the future.
closes #112
=> Git and minio configuration with quick-start

api/v1alpha1/bucketstatestore_types.go, api/v1alpha1/destination_types.go, api/v1alpha1/gitstatestore_types.go, api/v1alpha1/promise_types.go, api/v1alpha1/promiserelease_types.go, api/v1alpha1/work_types.go, api/v1alpha1/workplacement_types.go, config/crd/bases/platform.kratix.io_bucketstatestores.yaml, config/crd/bases/platform.kratix.io_destinations.yaml, config/crd/bases/platform.kratix.io_gitstatestores.yaml, config/crd/bases/platform.kratix.io_promisereleases.yaml, config/crd/bases/platform.kratix.io_promises.yaml, config/crd/bases/platform.kratix.io_workplacements.yaml, config/crd/bases/platform.kratix.io_works.yaml
Add CRDs to 'kratix' category, so all resources can be easily fetched with 'kubectl get kratix'. 
It's up to the team if including all CRDs is the desired way. We should discuss as a group before approving and merging this PR.
For example:
```
❯ k get kratix
NAME                                          AGE
bucketstatestore.platform.kratix.io/default   25m
NAME                                              AGE
destination.platform.kratix.io/platform-cluster   23m
destination.platform.kratix.io/worker-1           25m
NAME                                       AGE
gitstatestore.platform.kratix.io/default   25m
NAME                                 STATUS        KIND      API VERSION                      VERSION
promise.platform.kratix.io/easyapp   Unavailable   EasyApp …
```
=> feat: add CRDs to 'kratix' category

controllers/dynamic_resource_request_controller.go, controllers/dynamic_resource_request_controller_test.go, controllers/promise_controller.go, lib/resourceutil/util.go, lib/resourceutil/util_test.go, test/system/system_test.go, work-creator/scripts/reader
We now show `Observed Generation` in the resource status.
closes #109
```
> k get data.marketplace.kratix.io my-resource -o yaml
apiVersion: marketplace.kratix.io/v1alpha1
kind: data
metadata:
...
generation: 1
name: my-resource
namespace: default
spec:
value: abc
status:
conditions:
- lastTransitionTime: "2024-05-03T14:04:27Z"
message: Pipeline completed
reason: PipelineExecutedSuccessfully
status: "True"
type: PipelineCompleted
message: Resource requested
observedGeneration: 1
```
=> feat: Set observed generation in resource requests

controllers/promise_controller.go, controllers/promise_controller_test.go
Before a promise that has no static dependencies would still create an empty work:
```
apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
creationTimestamp: null
name: redis
namespace: default
labels:
kratix.io/promise-version: v0.1.0
spec:
api:
...
workflows:
resource:
configure:
- apiVersion: platform.kratix.io/v1alpha1
kind: Pipeline
metadata:
name: instance-configure
namespace: default
spec:
containers:
- image: ghcr.io/syntasso/kratix-marketplace/redis-configure-pipeline:v0.1.0
name: redis-configure-pipeline
promise:
configure:
- apiVersion: platform.kratix.io/v1alpha1
kind: Pipeline
metadata:
name: promise-configure
namespace: default
spec:
containers:
- image: ghcr.io/syntasso/kratix-marketplace/redis-configure-pipeline:v0.1.0
name: redis-configure-pipeline
```
```
kaf …
```
=> fix: don't create an empty static-deps work when no static dependencies exist

.circleci/config.yml
Originally we used the dev branch as a way to mitigate risk against breaking users with changes. This was before we had introduced the release process which is itself a safety gate for this.
This change removes the dev branch from the CI process, enabling engineers to open PRs directly against main branch. 
Note that this does not change the GitHub settings so main continues to be the "default" branch:
And we will continue to have branch protection rules on `main` which means only Kratix maintainers can push directly to that branch.
=> Remove dev branch as gate to main

controllers/promise_controller.go, controllers/promise_controller_test.go
this allows promise writers to control what kubectl shows when `kubectl get <promise crd>` is executed on the terminal
=> feat: respect promise api AdditionalPrinterColumns

api/v1alpha1/destination_types.go, config/crd/bases/platform.kratix.io_destinations.yaml
struct field name was renamed but we missed the json key name from previous PR
=> fix: rename json key filepath.type to filepath.mode

api/v1alpha1/work_types.go
=> bugfix: use unique name for static dependencies

config/crd/kustomization.yaml, config/manager/kustomization.yaml, config/rbac/kustomization.yaml
this commit applies some of the [recommended
labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/)
to the kratix objects and crds
=> feat: label kratix resources

lib/writers/git.go, test/system/assets/git/destinations.yaml, test/system/system_test.go
Closes #163
- read .kratix state file correctly at deletion and update for git state store
- test `filepath.mode: none` for git state store in system test
=> fix: read .kratix with correct path at deletion

lib/pipeline/args.go, lib/pipeline/configure.go, lib/pipeline/configure_test.go, lib/pipeline/delete_test.go, lib/pipeline/shared.go
Implements #84
This PR updates the pipeline naming format to ensure they are named in the format, `kratix-<promiseName>-<pipelineName>-UUID` for Promise Configure and Delete pipelines and `kratix-<promiseName>-<resourceName>-<pipelineName>-UUID` for Resource Configure and Delete Pipelines. This makes no changes to the existing labels.
When the name of the pipeline will exceed the 63 character limit, the name is truncated.
**Promise Configure**
Promise: Redis Marketplace promise
Install Promise
```
kubectl apply -t promise.yaml
```
Get pods
```
➜  ~ k get pods -A
NAMESPACE                NAME                                                 READY   STATUS      RESTARTS   AGE
kratix-platform-system   kratix-redis-promise-configure-f8ddb-clvws           0/1     Completed   0          35s
``` …
=> Clearer pipeline visibility

controllers/workplacement_controller.go, controllers/workplacement_controller_test.go, lib/writers/s3.go, test/system/system_test.go
When we cannot find .kratix state file, we can't generate the list of files to clean up for flat state store. Requeuing won't help and we need to exit
=> fix: delete kratix statefile last

main.go
Setting `PprofBindAddress` in manager options to serve `pprof`.
To use: 
1. port forward the controller pod
2. collect a profile
4. visualize:
```
❯ k -n kratix-platform-system port-forward pod/kratix-platform-controller-manager-5c4df4bc77-wtp6z 8082:8082
❯ curl -s "http://127.0.0.1:8082/debug/pprof/heap" > ./heap.out
❯ go tool pprof -http=:8080 ./heap.out
Serving web UI on http://localhost:8080
``` 
Then you can get CPU time, heap, flamegraph...etc
=> feat: serve pprof

main.go
If mass pass delete promises today, it goes:
1. k delete promises --all
1. kratix delete promise
1. restart manager (takes 30~ seconds)
1. kratix delete promise
1. restart manager (takes 30~ seconds)
1. kratix delete promise
1. restart manager (takes 30~ seconds)
1. kratix delete promise
1. restart manager (takes 30~ seconds)
...
with this new approach it should:
1. k delete promises --all
1. kratix delete promise
1. kratix delete promise
1. kratix delete promise
1. kratix delete promise
1. kratix delete promise
1. restart manager (takes 30~ seconds)
The downside of this is that for the 2 minutes period you will see some annoying log output, but I think its worth it for the instant improved UX of mass deletes
=> feat: speed up mass deletes by delaying the manager restart by 2 minutes

.images, Makefile, demo/demo-image-list, lib/writers/git.go, scripts/quick-start.sh
Current stable cert-manager is 3 minors above our default version. Upgrading first in Kratix after testing with quick-start, and will then go to update in docs.
=> Chore: Upgrade baseline cert-manager to 0.15.0

.circleci/config.yml
Tested it working in a separate job before moving into the security scanner:
sad path:
happy path:
=> check go version in circleci matches docker image version

.circleci/config.yml, scripts/make-distribution, scripts/tag-latest-version
Changes:
- Move to only have a `latest` release (and tag)
- Append the manifest digest to each of the images (Kratix and Work Creator)
=> feat: remove versioning in OS Kratix

lib/writers/git.go
Searching for the error came up with a lot of results for this issue when using `go-git` https://www.google.com/search?q=unexpected+client+error+400+devops+git+clone&oq=unexpected+client+error+400+devops+git+clone&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIHCAEQIRigATIHCAIQIRigATIHCAMQIRigAdIBCDU0MzdqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8
Found the fix here https://github.com/pulumi/pulumi/pull/12001. Original issue in go-git https://github.com/go-git/go-git/issues/64
before:
```
2024-07-12T16:43:25Z    INFO    controllers.DestinationController.writers.GitStateStoreWriter   creating local directory        {"destination": {"name":"worker"}, "dir": "worker", "branch": "main"}
2024-07-12T16:43:25Z    INFO    controllers.DestinationController.writers.GitStateStoreWriter   cloning repo    {"destination": …
```
=> Support azure devops repos

controllers/destination_controller.go, controllers/work_controller.go, controllers/workplacement_controller.go, controllers/workplacement_controller_test.go, lib/writers/git.go
closes #203 
green runs (the red is a different testing flaking, I'm investigating and will address in a different PR) 
this bug was pretty nasty to debug, and highlighted two issues:
- Destination controller triggers the reconciliation of ALL works, even if the work in question is being deleted, which causees it to recreate a workplacement immediately after its been deleted (race conditon)
- A workplacement gets the finalizer added for deleting the files it creates *before* it creates them, which means if a workplacement is created, finalizers added (requeue triggered), workplacement deleted, requeue starts the deletion path despite no files having been created.
Chronological order:
1. An existing healthy work get deleted, triggers deletion of workplacement
2. Workplacement gets …
=> Don't reconcile Works that are being deleted; set workplacement finalizers after writing files

api/v1alpha1/pipeline_types.go, api/v1alpha1/pipeline_types_test.go, api/v1alpha1/work_types.go, controllers/promise_controller.go, controllers/shared.go, lib/objectutil/name.go, lib/objectutil/name_test.go, lib/workflow/rbac.go, lib/workflow/reconciler.go, lib/workflow/reconciler_test.go, test/system/assets/bash-promise/promise-v1alpha2.yaml, test/system/assets/bash-promise/promise.yaml, test/system/system_test.go
This PR introduces support for cross-namespace permissions in Kratix Pipelines via the Pipeline's `spec.rbac.permissions`.
It's now possible to access resources outside of the Pipeline namespace by setting the permissions in the Promise, removing the need to set up cross-namespace RBAC manually.
```yaml
- apiVersion: platform.kratix.io/v1alpha1
kind: Pipeline
metadata:
name: foo
spec:
rbac:
permissions:
- apiGroups: [ "" ]
resources: [ "configmaps" ]
verbs: [ "list" ]
resourceNamespace: "*"
```
This gives the Pipeline's ServiceAccount permission to `list configmaps` across all namespaces.
```yaml
- apiVersion: platform.kratix.io/v1alpha1
kind: Pipeline
metadata:
name: foo
spec:
rbac:
permissions:
- apiGroups: [ "" ]
resources: [ "configmaps" ]
verbs: [ "list" ]
resourceNamespace: …
```
=> feat: cross-namespace pipeline permissions

test/system/system_suite_test.go
We have introduced the ability to skip local/kind based set up files when running system tests. There was one additional file that was impacted and not making sure this is present on the LRE caused failures in the soak testing.
Making sure that one file is installed, but still allowing us to skip the local config files using the 'PLATFORM_SKIP_SETUP' var.
=> fix: apply bash-promise for all envs

controllers/shared.go, lib/writers/git.go
Destination is a cluster scoped resource, it's namespace is not set
=> Refactor: stop using namespace from destination

controllers/dynamic_resource_request_controller.go, controllers/promise_controller.go, lib/workflow/reconciler.go, lib/workflow/reconciler_test.go, main.go
Number of jobs to keep before cleaning up can now be configured through environment variable in kratix operator.
Name of env var `NUMBER_OF_JOBS_TO_KEEP`.
To try it out:
```
k -n kratix-platform-system set env deployment/kratix-platform-controller-manager NUMBER_OF_JOBS_TO_KEEP=1 # any limit you would like
```
Trigger reconciliation for our promise or resource to see it in effect.
1. research day work; may not be something that's useful
2. Name of env var `NUMBER_OF_JOBS_TO_KEEP`, there could be a better name
3. No upper limit. Given this is something that has a default and only people who would like to custom it will use it, I think that's fine. Maybe there are concerns.
4. When we cannot parse the env var, of if env var is set to less than one, we set it to default value and continue. …
=> feat: make number of job limit per pipeline configurable

api/v1alpha1/promise_types.go, config/crd/bases/platform.kratix.io_promises.yaml
Adding crd descriptions for Promise.
Description mostly taken from https://docs.kratix.io/main/guides/writing-a-promise#whats-inside-a-kratix-promise.
Relates to chore #106
=> chore: add crd description for Promise

controllers/promise_controller.go, controllers/work_controller.go, controllers/workplacement_controller.go
follow up from #253 
Requeue when update fails with a conflict error instead of returning the error to reduce the occurence of update conflict error "the object has been modified"
```
2024-10-11T14:08:10Z	ERROR	Reconciler error	{"controller": "promise", "controllerGroup": "platform.kratix.io", "controllerKind": "Promise", "Promise": {"name":"bashb398b"}, "namespace": "", "name": "bashb398b", "reconcileID": "f067966e-ef3a-4ce8-b42b-939ec8cc6f01", "error": "Operation cannot be fulfilled on promises.platform.kratix.io \"bashb398b\": the object has been modified; please apply your changes to the latest version and try again"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controlle …
```
=> chore: requeue on update conflict

controllers/promise_controller.go, test/system/assets/bash-promise/execute-pipeline, test/system/assets/bash-promise/promise-v1alpha2.yaml, test/system/assets/bash-promise/promise.yaml, test/system/assets/bash-promise/roles-for-promise.yaml, test/system/system_test.go
This PR does two things:
1. Adds `delete-workflows` and `workflows-cleanup` to the list of Promise finalizers which are checked when deleting a Promise.
2. Fixes the system tests to ensure that no resources are left over after tests have passed.
(1) was a bug we found while fixing (2), and was tested manually. It presented as failing to delete the Promise, which was found to be due to two combined factors:
- The Promise being deleted before all finalizers had been set (so only `delete-workflows` and `workflows-cleanup` were set).
- The `promiseFinalizers` list being incomplete (missing `delete-workflows` and `workflows-cleanup`), meaning these finalizers were never removed during delete.
The bug in (1) would have been hit if the Promise was deleted when only the `delete-workflows` and …
=> fix: ensure all promise finalizers checked when deleting

api/v1alpha1/pipeline_factory.go, api/v1alpha1/pipeline_types.go, api/v1alpha1/pipeline_types_test.go, api/v1alpha1/work_types.go, lib/workflow/rbac.go, lib/workflow/reconciler_test.go, test/system/assets/bash-promise/promise.yaml, test/system/assets/bash-promise/roles-for-promise.yaml, test/system/system_test.go
Closes: #266 
This PR:
- generates role binding and cluster role binding names for user provided permission based on pipeline(or service account) namespace rather than the namespace that the rbac is for
- add a new resource namespace label to user provided permission object to distinguish bindings created for service accounts in different namespaces when deleting
- created a `pipeline_factory.go` for `PipelineFactory` and its methods
- adds a system test creating one resource request from default namespace, one from 'test' namespace.
=> fix: create separate bindings for resources requests from different namespaces with user provided RBAC

hack/destination/gitops-tk-resources-git.yaml, hack/destination/gitops-tk-resources-single-cluster.yaml, hack/destination/gitops-tk-resources.yaml, hack/templates/gitops-tk-resources-template.yaml, test/system/assets/git/platform_gitops-tk-resources.yaml
These warnings come up during the workshop. Nice to get rid of them to reduce noise.
=> chore: update deprecated flux resources

test/system/system_suite_test.go, test/system/system_test.go
Some small fixes around system test clean up logic:
- delete 'test' namespace in AfterEach() so this namespace gets cleaned up at failure and won't impact next system test run
- clean up promise release deployment in AfterSuite rather than test AfterEach() because there're two test specs using this deployment
=> chore: fix system test clean up

.circleci/config.yml
- helm chart repo now has test suite. Cloning it into repo/charts makes ginkgo run its test suite with -r flag
- this commit makes clone helm chart happen after running kratix unit and sys test to avoid running chart tests as part of kratix ci test
=> chore: clone helm chart after unit test

controllers/dynamic_resource_request_controller_test.go, controllers/promise_controller.go, controllers/promise_controller_test.go, lib/resourceutil/util.go
Closes #273 
Introduce label `kratix.io/reconcile-resources`. When set to true on a promise, kratix will re reconcile all its resources label This label will be automatically removed after kratix has set manual reconciliation label on resources.
=> feat(#273): reconcile all resources from promise label

.circleci/config.yml, scripts/quick-start.sh
- use k8s 1.31 in quick-start
- bump `kind` cli version in circle CI. Default node image is v1.31.2 in kind 0.25.0: https://github.com/kubernetes-sigs/kind/releases/tag/v0.25.0
=> chore: use k8s 1.31 in quick-start and CI

api/v1alpha1/destination_types.go, config/crd/bases/platform.kratix.io_destinations.yaml, controllers/destination_controller.go, controllers/destination_controller_test.go, controllers/scheduler.go
Closes #232.
Introducing the `cleanup` field in the `Destination` spec.  If set to `all`, `workplacements` and State Store contents will be removed after removing the destination. Defaults to `none`.
=> feat: delete resources when the destination is deleted

main.go
the way we handle the deletion of promises requires this to be disabled
Co-authored-by: Chunyi Lyu <chunyi@syntasso.io>
=> fix: skip name validation on manager ctrl options

work-creator/pipeline/cmd/reader/main.go, work-creator/pipeline/cmd/update-status/main.go, work-creator/pipeline/lib/helpers/helpers.go, work-creator/pipeline/lib/reader.go, work-creator/pipeline/lib/reader_test.go
Refactors the reader pipeline component into a testable library and adds unit tests
- Extracts reader functionality into a dedicated library package
- Introduces shared helpers for kubernetes client and parameter handling
- Adds unit tests for the reader component
closes #122
=> chore: refactor helpers common code into a pkg

lib/writers/s3.go
I think this is just a race condition that occasionally happens, but my systems tests failed 1 out of 3 times with this error
=> chore: Don't try to delete non-existen objects

.circleci/config.yml, scripts/make-distribution
Today the SHA the kratix manifests pin the kratix docker images at are the AMD specific SHA:
Manifest:
SHA:
The consequence of this is that if you deploy Kratix to an arm-only setup, e.g. running OpenShift locally on MacOS M2 Mac, it fails to start (KinD on MacOS is happy to run AMD image):
If you select `arm` in the dropdown in dockerhub, you get a different sha
The solution for us to use the index digest, which is platform agnostic
This index digest isn't fetchable using `docker` cli, but [skopeo](https://github.com/containers/skopeo) is a tool used to interact with remote registries and can retrieve it:
Skopeo doens't host static binaries... so I'm installing using ubuntu package 🤷 opent o alternatives https://github.com/containers/skopeo/blob/main/install.md
=> fix: Pin kratix distribution at generic docker sha, not AMD specific

test/core/core_test.go, test/kubeutils/cluster.go
with the recent change to use a single worker as two different
destinations, the tests were no longer covering multi-destination
scheduling.
To validate that Kratix is indeed scheduling the workloads to the
appropriate place, we no longer can rely solely on the workload showing
up on the worker. Instead, we must check the WorkPlacements and verify
that the target destination for that workload is indeed the right
destination.
also removed a few duplicated assertions.
=> chore: improve core system tests

api/v1alpha1/pipeline_factory.go, api/v1alpha1/pipeline_types.go, api/v1alpha1/pipeline_types_test.go, api/v1alpha1/work_types.go, controllers/dynamic_resource_request_controller.go, controllers/dynamic_resource_request_controller_test.go, controllers/promise_controller.go, controllers/shared.go, lib/workflow/rbac.go, lib/workflow/reconciler.go, lib/workflow/reconciler_test.go
This PR refactors the workflow pipeline job labels as follows: 
```
kratix.io/pipeline-name
kratix.io/promise-name
kratix.io/workflow-action
kratix.io/workflow-type
```
Also, it adds the Kubernetes recommended `managed-by` label to the Jobs: 
```
app.kubernetes.io/managed-by=Kratix
```
Note: 
- This is not a breaking change because we are still supporting the legacy labels.
=> chore: consolidate and refactor labels for pipelines

controllers/dynamic_resource_request_controller.go, controllers/dynamic_resource_request_controller_test.go, controllers/promise_controller.go, controllers/promise_controller_test.go, controllers/suite_test.go, lib/resourceutil/util.go, lib/workflow/reconciler.go, lib/workflow/reconciler_test.go
Fixes [#356](https://github.com/syntasso/kratix/issues/356)
Added a new condition: DeleteWorkflowCompletedCondition
When a resource delete pipeline fails, we now:
- update the DeleteWorkflowCompletedCondition to convey that the delete pipeline failed
- send an event to the resource to notify of the delete pipeline failure
- return an error in the reconciler
=> feat: handle failed resource delete pipelines

api/v1alpha1/pipeline_types.go, api/v1alpha1/pipeline_types_test.go, api/v1alpha1/promise_types.go, internal/webhook/v1alpha1/promise_webhook_test.go
Follow up of PR #363 
Better error message at failed to unmarshall pipelines:
```
❯ k apply -f test/core/assets/promise.yaml
Error from server (Forbidden): error when creating "test/core/assets/promise.yaml":
admission webhook "vpromise.kb.io" denied the request:
failed parsing promise.configure pipeline:
failed unmarshalling pipeline setup-deps: json: unknown field "rbac"
```
Instead of:
```
❯ k apply -f test/core/assets/promise.yaml
Error from server (Forbidden): error when creating "test/core/assets/promise.yaml": admission webhook "vpromise.kb.io" denied the request: json: unknown field "rbac"
```
=> chore: better msg with pipeline unmarshall error

.github/workflows/pr.yaml, .github/workflows/trigger-ci.yaml, Makefile, scripts/install-gitops, scripts/quick-start.sh, scripts/register-destination, scripts/utils.sh, test/core/core_suite_test.go, test/core/core_test.go
Closes [#318](https://github.com/syntasso/kratix/issues/318)
We will use `act` to run CI workflows on local dev environments. The following make targets are introduced to run the workflows:
```
make act-test-and-lint
make act-integration-test
make act-system-test
```
If you want to run all in once, run the following command. Please note that this will run the jobs sequentially, not in parallel: 
```
make act-run-all
```
Note: After running the make targets, the platform and worker clusters will keep running on your docker environment.
=> chore: enable to run CI tests locally

internal/controller/destination_controller.go, internal/controller/destination_controller_test.go
It should be `destination.spec.path/destination.name`, not `destination.name/destination.spec.path`
Related to PR #352
=> fix: correct destination path migration

hack/platform/gitea-server-values.yaml
This is a small update which is being tested with both the quick start and the workshop prep for KubeCon London.
=> fix: missed 2 envvars from gitea helm chart values

.github/workflows/pr.yaml, go.mod
We are already building with 1.23 in Dockerfiles, so updating go.mod and version in github action.
=> chore: bump go to 1.23 in go.mod

api/v1alpha1/promise_types.go, internal/controller/promise_controller.go, internal/controller/promise_controller_test.go
closes #321 
Set exactly the same way as the promise available status this makes it easier to set up automation such as kubectl wait on promise availability.
When it's unavailable:
```
status:
apiVersion: marketplace.kratix.io/v1alpha1
conditions:
- lastTransitionTime: "2025-02-26T16:47:31Z"
message: Cannot fulfil resource requests
reason: PromiseUnavailable
status: "False"
type: Available
...
kind: redis
status: Unavailable
```
When promise is available:
```
status:
apiVersion: marketplace.kratix.io/v1alpha1
conditions:
- lastTransitionTime: "2025-02-26T16:56:22Z"
message: Ready to accept resource requests
reason: PromiseAvailable
status: "True"
type: Available
...
kind: redis
lastAvailableTime: "2025-02-26T16:56:22Z"
status: Available
```
=> feat: introduce promise available status condition

test/system/destination_test.go
k8s will delete events after 60 minutes, so we shouldn't start the tests with an expectation that an event was created before the test started.
The events are still checked later in the destination tests.
=> fix: remove initial events check in destination test

api/v1alpha1/promise_types.go, internal/controller/promise_controller.go, internal/controller/promise_controller_test.go
I've observed a few times in which a user has issues deleting a Promise, they decide to just force remove all finalizers in order to let the Promise be deleted, and then recreate the Promise. 
This results in both the old and new dynamic controller running because the UID has changed. To get around this issue we should track the dynamic controller by promise name instead.
I've gone for `promisename_crdname` because the above scenario might still happen, but if someone changes the CRD gvk (therefore name) between that, we still need to start a *new controller* that watches the new CRD gvk.
We should probably also have some extra cleanup steps to detect this "ghost" controllers, but that felt like an extra piece of work outside of this bug fix. I've created an …
=> fix: Prevent mulitple dynamic controllers from starting for a Promise

lib/resourceutil/util.go, lib/workflow/reconciler.go, lib/workflow/reconciler_test.go
fixes #383 
The manual re-run delete label key is `kratix.io/manual-rerun-delete`. We also added events to the delete pipeline starts. 
Docs PR to follow, we'll mention it in the comments.
=> feat: add manual re-run delete pipeline label

go.mod, go.sum
Snyk is failing because of this vulnerability: https://security.snyk.io/vuln/SNYK-GOLANG-GOLANGORGXNETHTTPHTTPPROXY-9058601
It is affecting `golang.org/x/net` package. It is an indirect dependency, and used by multiple dependencies. Bumping the version to v0.36.0 with this PR.
=> fix: bump golang.org/x/net to v0.36.0 to fix CVE-2025-22870

lib/resourceutil/util.go, lib/workflow/reconciler.go, lib/workflow/reconciler_test.go
closes #383.
* The previous manual-rerun-delete label is removed and now using manual-reconciliation label instead
* Labeling a resource with manual-reconciliation now will suspend the running delete workflow job and re-create it
=> feat: align manual delete workflows with configure behaviour

test/core/core_test.go
The `Eventually` calls in the core tests will default to 1s, which may not be long enough. This commit explicitly specifies a longer timeout and interval.
=> chore: ensure core tests wait for success

api/v1alpha1/pipeline_factory.go, api/v1alpha1/pipeline_types.go, api/v1alpha1/pipeline_types_test.go, cmd/main.go
closes #402. As the commit, tested in unit tests not in system tests.
related docs PR: https://github.com/syntasso/kratix-docs/pull/201
To test:
1. create a kratix configmap with default image pull policy set:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: kratix
namespace: kratix-platform-system
data:
config: |
numberOfJobsToKeep: 1
workflows:
defaultImagePullPolicy: Never
```
2. restart kratix platform to read in the latest configmap values
3. create a promise or a request and see:
```
❯ k get jobs kratix-redis-example-instance-configure-83699 -oyaml | grep imagePullPolicy
imagePullPolicy: Never
imagePullPolicy: Never
imagePullPolicy: Never
imagePullPolicy: Never
```
=> feat: set default imagePullPolicy with kratix config

internal/webhook/v1alpha1/promise_webhook.go, internal/webhook/v1alpha1/promise_webhook_test.go
kratix does not support promise API that's cluster scoped. When creating a promise with cluster scope crd, kratix accepts the promise, but fails to reconcile its resource requests:
```
{"uid": "4a56b", "promiseID": "redis", "namespace": {"name":"example"}, "resourceRequest": "redis-example", "isManualReconciliation": false, "type": "*v1.Job", "gvk": "/, Kind=", "name": "kratix-redis-example-instance-configure-fb3b1", "namespace": "", "labels": {"app.kubernetes.io/managed-by":"Kratix","kratix.io/hash":"7e3e1952970a4f67f57d2d0ca6c5681c","kratix.io/pipeline-name":"instance-configure","kratix.io/promise-name":"redis","kratix.io/resource-name":"example","kratix.io/workflow-action":"configure","kratix.io/workflow-type":"resource"}, "error": "an empty namespace may not be set during creation"} …
```
=> feat: validation on promise api scope

api/v1alpha1/destination_types.go, config/crd/bases/platform.kratix.io_destinations.yaml, config/samples/platform_v1alpha1_worker.yaml, config/samples/platform_v1alpha1_worker_2.yaml, internal/controller/destination_controller.go, internal/controller/destination_controller_test.go, internal/webhook/v1alpha1/destination_webhook.go, internal/webhook/v1alpha1/destination_webhook_test.go, scripts/register-destination
- Make destination.spec.path a required field. Create and update will fail without path being set.
- Remove all prior migration logic
1. when creating a destination without `spec.path` or `spec.path` set to ""
```
❯ cat test.yaml
apiVersion: platform.kratix.io/v1alpha1
kind: Destination
metadata:
labels:
environment: dev
name: test
spec:
path: ""
cleanup: none
filepath:
mode: nestedByMetadata
initWorkloads:
enabled: true
stateStoreRef:
kind: BucketStateStore
name: default
❯ k apply -f test.yaml
The Destination "test" is invalid:
* spec.path: Required value
* <nil>: Invalid value: "null": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation
```
=> feat: make destination.spec.path a required field

internal/controller/destination_controller.go, test/system/assets/destination/destination-cleanup-all.yaml, test/system/assets/destination/promise-cleanup-all.yaml, test/system/assets/destination/resources-cleanup-all.yaml, test/system/destination_test.go
closes #429 
Previously we were only queueing request when destination.spec was updated; we remove the filtering so it will queue on any changes to the destination.
This PR also adds a new system test spec to test out the behavior of a destination when `spec.cleanup` is set to `all`.
For destination reconciliation, we want it to be triggered when:
1. its statestore spec has changed
2. its statestore status has changed (from 'not ready' to 'ready' or vice versa)
3. any changes to the destination itself. Arguably, we only need to watch `.spec` and `metadata.finalizers` for now. However, we might need to respond to `labels` and `annotations` changes in the future. We believe filtering on the exact fields might lead to more issues in the future because it might not be obvious that we need to …
=> fix: reconcile destination when spec.cleanup set to all

scripts/quick-start.sh
This was raised as a blocker by a new user. I have decided not to actively set the limits for them, but to instead alert them if there is an issue and give them the tools to solve it. This is because I assume people wouldn't like these kinds of limits to be set automatically.
So far I have:
* tested individual commands on linux docker containers locally
* verified mac installation continues to work locally
* bodged together a test in docker locally to see the command ran correctly
* verified on linux in CI (including lowering minimum limits to match what we run with on CI)
Before merging I want to:
=> fix: check for inotify limits on linux for quickstart

api/v1alpha1/pipeline_factory.go, api/v1alpha1/pipeline_types.go, api/v1alpha1/pipeline_types_test.go, work-creator/pipeline/lib/helpers/helpers.go
Standardise KRATIX_ prefix for envvars and expose the object name in the pipeline images by default. This allows people to do more useful inline containers as they can use vars that are unique.
=> feat: expose more envvars for pipeline containers

Makefile, scripts/make-distribution, work-creator/Makefile
In order to get metrics of how many people run the quick start, this PR updates the manifest to use a separate identical imagine, so we can gather metrics.
Verified the changes to the script
```
diff prior-to-change-install-all-in-one.yaml post-changes-to-install-all-in-one.yaml
1612c1612
<   PIPELINE_ADAPTER_IMG: syntasso.docker.scarf.sh/syntasso/kratix-platform-pipeline-adapter@sha256:89dd4c316914ea259b9a2ee95089c0ecc711152e016f1f8568f27516b9318280
---
>   PIPELINE_ADAPTER_IMG: syntasso.docker.scarf.sh/syntasso/kratix-platform-pipeline-adapter-quickstart@sha256:98ed3239c179a4014ecfa29463c31f5c84127b2db5d4f228b44370f5ea50620c
1699c1699
<           image: syntasso.docker.scarf.sh/syntasso/kratix-platform@sha256:5c63a74db894aaf9b6abf88466f7837ee9a73659204ab89d3053a1be56a1623a
---
> …
```
=> chore: Separate quick start image for install-all-in-one.yaml

api/v1alpha1/promise_types.go, internal/controller/promise_controller.go, lib/resourceutil/work.go, lib/workflow/reconciler.go, work-creator/pipeline/work_creator.go
For workflows that are dependant on changes outside of the promise spec, this introduced a check on the `kratix.io/pipeline-hash` label (if it is set) to determine whether and updated has been made that should result in the creation of a new job.
Additionally, this PR ensures the labels used when querying works and the same as those used when creating works.
=> Check Pipeline hash and make labels consistent when querying and updating works

PROJECT, api/v1alpha1/bucketstatestore_types.go, cmd/main.go, config/webhook/manifests.yaml, internal/controller/bucketstatestore_controller.go, internal/webhook/v1alpha1/bucketstatestore_webhook.go, internal/webhook/v1alpha1/bucketstatestore_webhook_test.go
closes #461 
This PR introduces a webhook for BucketStateStore ensuring a secret is provided when auth method is set to `accessKey`.
It fixes bucket state store with IAM auth method by not assuming secrets are always provided when building a secret index to watch. See the below panics for reference
```
E0515 09:08:52.027744       1 panic.go:262] "Observed a panic" panic="runtime error: invalid memory address or nil pointer dereference" panicGoValue="\"invalid memory address or nil pointer dereference\"" stacktrace=<
goroutine 120 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x218f700, 0x3509e60}, {0x1a96820, 0x3476300})
/go/pkg/mod/k8s.io/apimachinery@v0.31.0/pkg/util/runtime/runtime.go:107 +0x98
```
Iam with no secret provided does not panic
```
apiVersion: …
```
=> fix: controller panics when not providing secret for bucketstatestore auth using IAM

internal/controller/promise_controller.go
closes #431
The previous check is wrong for promise with original status unavailable. 
`if requirementsChanged && originalStatus == v1alpha1.PromiseStatusAvailable` 
Requirements can change but it will never get updated since compound promise with missing required promises never becomes `available`.
To verify the fix, you can:
```
k apply -f ~/workspace/kratix-marketplace/app-as-a-service/promise.yaml
k apply -f ~/workspace/kratix-marketplace/app-as-a-service/promises/postgresql-promise-release.yaml
```
Then wait for postgresql to be available, and
```
k get promises app -oyaml
apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
annotations:
...
status:
apiVersion: marketplace.kratix.io/v1
conditions:
- lastTransitionTime: "2025-05-16T15:54:46Z"
message: Cannot fulfil resource …
```
=> fix: update promise requirements when promise unavailable

go.mod, internal/webhook/v1alpha1/promise_webhook_test.go
The package golang.org/x/exp/rand is deprecated and no longer maintained, so it makes sense to move to the recommeded replacement of math/rand/v2
The function "randomString()" was renamed to "randomishString()" to make it crystal clear that it's not cryptographically random.
=> chore: replace deprecated golang.org/x/exp/rand with math/rand/v2

api/v1alpha1/pipeline_factory.go, go.mod
The standard library supplies the `fmt.Errorf()` function to wrap errors, so there's no need to import the `github.com/pkg/errors` package purely for error wrapping.
=> chore: use error wrapping from standard library

api/v1alpha1/pipeline_factory.go, api/v1alpha1/pipeline_types_test.go, api/v1alpha1/promise_types.go, go.mod, go.sum, internal/controller/dynamic_resource_request_controller_test.go, internal/controller/promise_controller_test.go, internal/controller/workplacement_controller.go, lib/workflow/reconciler.go
This reverts commit 5d6864a21ba9a4c594e767809eb23ba810fb3f84.
The recent change to our yaml parser resulted in malformat dependencies:
```
...
workflows: # taken from state store
resource:
configure:
- apiVersion: platform.kratix.io/v1alpha1
kind: Pipeline
metadata:
name: instance-configure
namespace: default
spec:
containers:
- image: syntasso/demo-nginx-configure-pipeline:v0.1.1
name: demo-nginx-configure-pipeline
status: {} # there should be '---' below this line
apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
name: postgresql
namespace: default
spec:
api:
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
name: postgresqls.marketplace.kratix.io
spec:
group: marketplace.kratix.io
...
```
The above can be reproduced by applying easy-app `k apply …
=> revert: "chore: consolidate on a single YAML parser (#485)"

api/v1alpha1/pipeline_factory.go, api/v1alpha1/pipeline_types_test.go
`KRATIX_WORKFLOW_TYPE`, `KRATIX_CRD_PLURAL`, and `KRATIX_CLUSTER_SCOPED` were set twice in the reader container. This has caused a flood of warning logs:
```
2025-06-06T14:04:30Z	INFO	promise-webhook	default
2025-06-06T14:04:30Z	INFO	KubeAPIWarningLogger	spec.template.spec.initContainers[0].env[11]: hides previous definition of "KRATIX_WORKFLOW_TYPE", which may be dropped when using apply
2025-06-06T14:04:30Z	INFO	KubeAPIWarningLogger	spec.template.spec.initContainers[0].env[12]: hides previous definition of "KRATIX_CRD_PLURAL", which may be dropped when using apply
2025-06-06T14:04:30Z	INFO	KubeAPIWarningLogger	spec.template.spec.initContainers[0].env[13]: hides previous definition of "KRATIX_CLUSTER_SCOPED", which may be dropped when using apply
2025-06-06T14:04:30Z	INFO	promise-webhook …
```
=> chore: remove duplicated envvars from reader container

api/v1alpha1/pipeline_types.go, api/v1alpha1/pipeline_types_test.go, api/v1alpha1/promise_types.go, api/v1alpha1/promise_types_test.go, cmd/main.go, go.mod, internal/controller/dynamic_resource_request_controller_test.go, internal/controller/promise_controller_test.go, internal/ptr/ptr.go, internal/ptr/ptr_suite_test.go, internal/ptr/ptr_test.go
- because k8s.io/utils does not use semver, Dependabot will not update it
- a relatively big dependency can be avoided with a tiny bit of duplication
- True() and False() functions were added to improve readability
=> chore: drop direct dependency on k8s.io/utils/ptr

.golangci-required.yml, internal/controller/dynamic_resource_request_controller.go, internal/controller/dynamic_resource_request_controller_test.go, internal/controller/promise_controller.go, internal/controller/promise_controller_test.go, internal/controller/shared_test.go, lib/resourceutil/util.go, test/system/assets/reconciliation/promise.yaml, test/system/assets/reconciliation/rr-one-updated.yaml, test/system/assets/reconciliation/rr-one.yaml, test/system/assets/reconciliation/rr-two.yaml, test/system/destination_test.go, test/system/reconciliation_test.go
closes #517
After pausing a promise you will see events and status condition on the promise to reflect it has been paused:
```
Warning  PausedReconciliation        7s (x3 over 81s)  PromiseController  'kratix.io/paused' label set to 'true' for promise; pausing reconciliation
Status:
API Version:  marketplace.kratix.io/v1alpha1
Conditions:
Last Transition Time:  2025-06-23T09:42:19Z
Message:               Paused
Reason:                PausedReconciliation
Status:                False
Type:                  Available
Last Transition Time:  2025-06-23T09:34:47Z
Message:               Pipelines completed
Reason:                PipelinesExecutedSuccessfully
Status:                True
Type:                  ConfigureWorkflowCompleted
Last Transition Time:  2025-06-23T09:42:19Z
Message: …
```
=> feat: pause reconciliation with label on promises

scripts/quick-start.sh
Use the `WAIT_TIMEOUT` variable instead of a fixed 1-minute timeout when waiting for provisioning to complete.
Tested with kind on macOS/arm and worked as expected.
Fixes #539
=> Fix: replaced fixed timeouts by WAIT_TIMEOUT variable

scripts/quick-start.sh
In slow environment, kratix deployment might take a long time to get ready and you might get error such as:
```
Error from server (InternalError): error when creating "/home/runner/work/enterprise-kratix/enterprise-kratix/read-only-kratix/config/samples/platform_v1alpha1_bucketstatestore.yaml": Internal error occurred: failed calling webhook "vbucketstatestore-v1alpha1.kb.io": failed to call webhook: Post "[https://kratix-platform-webhook-service.kratix-platform-system.svc:443/validate-platform-kratix-io-v1alpha1-bucketstatestore?timeout=10s](https://kratix-platform-webhook-service.kratix-platform-system.svc/validate-platform-kratix-io-v1alpha1-bucketstatestore?timeout=10s)": dial tcp 10.96.140.67:443: connect: connection refused
Error from server (NotFound): …
```
=> chore: wait for kratix deployment in quickstart

config/manager/manager.yaml
relates to https://github.com/syntasso/enterprise-kratix/issues/465
=> chore: bump kratix operator deployment memory request and limit

internal/controller/dynamic_resource_request_controller.go, internal/controller/dynamic_resource_request_controller_test.go, internal/controller/promise_controller.go, internal/controller/promise_controller_test.go
Fix for both promise and dynamic controller.
closes #575
=> fix: handle empty condition when getting work status

internal/controller/suite_test.go, internal/controller/workplacement_controller.go, internal/controller/workplacement_controller_test.go
Once the files are written successfully to the state store, we
immediately update a condition on the resource to reflect that. In rare
occasions, that status update can fail. When that happens, the version
id could be lost, since we were not storing it anywhere for the next
reconciliation
This commit fixes that behaviour. The Version ID is stored in the cache
immediately after it becomes available. It is only removed from the
cache when it's successfully persisted in the resource status.
=> fix: better handling of VersionID cache
